### ISSUE TITLE
Getting the error: Unable to add user to team. Retry!

### ISSUE THREAD

**Issue by juliofruta** [RattleSN4K3/git-in-team#1]
Hello!

I´m getting the 'Unable to add user to team'. Can you help me out? . I did the following:
1. Deployed to Heroku
2. Setup GITHUB_API_TOKEN, GITHUB_API_TYPE, GITHUB_APP_ID, GITHUB_APP_SECRET, GITHUB_ORGANIZATION (This as the name of the organization not it´s id)
3. In my application I did the following setup:
   Homepage URL: http://unamfi.herokuapp.com
   Authorization callback URL: http://unamfi.herokuapp.com
4. In another browser and with a github test account I tried to add my self to the organization. The application redirected me to a log in screen. I filled that up and got to the error page.

Am I doing something wrong? Thank you!

**Comment by RattleSN4K3** [comment]
Hi

The app was tested but only for a single organization. Sadly, the current version does have problems and also uses hardcoded non-general values. That said, the app requires a team named "People" to be available where new members will be added to. Not sure why I did that or if the API didn't support adding members to an orga (since it was before the simplified API regarding team/orgs). The rest of the setup also misses some steps to fully understand how to configure the app and github app.

If i'm correct, the following page should point you to the application settings "git-in-team" of your organization (or browse to your specific created one).
https://github.com/organizations/unamfi/settings/applications/220335

The **Client ID** and **Client Secret** should be listed there.

The **Homepage URL** and **Authorization callback URL** should be the following url (it may require the trailing slash) :

> http://unamfi.herokuapp.com/

Inside your heroku settings, https://dashboard.heroku.com/apps/unamfi/settings, you should have filled the following settings

| Key | Value |
| --- | --- |
| GITHUB_API_TOKEN | _*\* personal access token or generated token **_ |
| GITHUB_API_TYPE | Bearer |
| GITHUB_APP_ID | _*\* client id **_ |
| GITHUB_APP_SECRET | _*\* client secret **_ |
| GITHUB_ORGANIZATION | unamfi |

The initial setup is currently a bit strange tho. If you like to generate a api token, fill in "0" GITHUB_API_TOKEN. Visiting the page initially, it will ask you to setup the client id and secret. After that, it will generate a api token. Instead of accepting it, copy it and fill it into the heroku app settings.

After that verify if your Github organization has a team called "People". For the final step, restart the heroku app. It should work now (from what I have tested).

I should update several things of the app including the initial setup or error reporting.

Thanks for a general interest or at least trying the app.

**Comment by juliofruta** [comment]
Works wonderful with the 'People' team. That's the only change I had to make. Thanks @RattleSN4K3  ! 🤓
